name: Deel Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Lint Go code
      run: go fmt .
        

    - name: Run Go tests
      run: go mod tidy && go mod download && go test ./... -v

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag great15/deel:${{ github.sha }}

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push the Docker image to DockerHub
      run: docker push great15/deel:${{ github.sha }}
  
  update-chart-values:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update Helm chart values
      run: |
        KEY_TO_UPDATE="image.tag"
        NEW_VALUE=${{ github.sha }}

        awk -v key="$KEY_TO_UPDATE" -v value="$NEW_VALUE" '
          /^'"$KEY_TO_UPDATE"':/ { $2 = value; updated = 1 }
          { print }
          END { if (!updated) print key ": " value }
        ' ./deel/values.yaml > ./deel/values.tmp.yaml && \
        mv ./deel/values.tmp.yaml ./deel/values.yaml
          
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        git add .
        git commit -m "Update Helm chart value for image tag"
        git push
